### ISSUE TITLE
markdown, graphql

### ISSUE THREAD

**Issue by bennypowers** [panoply/vscode-json-script-tag#1]
Heya

Thanks for publishing this package

I sometimes work with graphql or markdown scripts:
```html
<script type="application/graphql"></script>
<script type="text/markdown"></script>
```

I'd love it if this plugin could extend to other grammars as well

**Comment by panoply** [comment]
Hej Benny, 

Glad you could find it useful. I can bring support for that into this extension. I'll have a look this week. 

FYI: I won't be able to apply IntelliSense without JavaScript intervention, so you will only get syntax highlighting. Meaning, code completions and validation etc won't work in those embedded regions, just the highlighting.

**Comment by bennypowers** [comment]
Yeah I figured that VSCode would be limited in that regard compared to Atom, but 🤷‍♂️ It'd still be a nice feature to have.

**Comment by panoply** [comment]
Hey Benny, instead of supporting this out of a JSON grammar, I instead provided GraphQL support via another extension, which you can download via the market place ([https://marketplace.visualstudio.com/items?itemName=sissel.graphql-script-tag](https://github.com/panoply/vscode-graphql-script-tag)) and also find on github [here](https://github.com/panoply/vscode-graphql-script-tag)

I haven't had time to do the Markdown variation but will get around to it. Hope it helps.

**Comment by panoply** [comment]
Hey Benny, instead of supporting this out of a JSON grammar, I instead provided GraphQL support via another extension, which you can download via the market place and also find it on github [here](https://github.com/panoply/vscode-graphql-script-tag).

I haven't had time to do the Markdown variation but will get around to it. Hope it helps.

https://marketplace.visualstudio.com/items?itemName=sissel.graphql-script-tag

**Comment by panoply** [comment]
@bennypowers You can now grab markdown support from the marketplace. 

https://marketplace.visualstudio.com/items?itemName=sissel.markdown-script-tag

**Comment by bennypowers** [comment]
Hey, thanks a mint, that's super helpful :D
